### ISSUE TITLE
regression attaching tracepoint:syscalls:sys_enter_landlock_add_rule in v0.24 (field has incomplete type)

### ISSUE THREAD

**Issue by martinetd** [bpftrace/bpftrace#4713]
### What reproduces the bug? Provide code if possible.

```
# bpftrace -e 'tracepoint:syscalls:sys_enter_* { print(probe); exit() }'
definitions.h:1946:33: error: field has incomplete type 'const enum landlock_rule_type'
definitions.h:1946:14: note: forward declaration of 'enum landlock_rule_type'
Clang parse error
```
In particular it seems to be caused by sys_enter_landlock_add_rule (as guessed from the error), e.g. for faster test:
```
bpftrace -e 'tracepoint:syscalls:sys_enter_landlock_add_rule {} BEGIN { exit() }'
```

First noticed on nixos test VM when updating to v0.24.1 from v0.23.5, but it reproduces just fine on a fedora host and I've bisected it down to these two commits (fails to build with just one; the three commits in the middle have been tested individually and are fine):
- 813f5714f506 cleanup: remove `tp_args_struct_level`
- 2b0a0f53032e Remove references to tp_args_structs_level

I tried reverting on master but src/tracepoint_format_parser.cpp changed quite a bit after these commits so I didn't push through; hopefully someone will figure this out better than me.

### `bpftrace --info` output

```
System
  OS: Linux 6.15.10-200.fc42.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 15 15:57:06 UTC 2025
  Arch: x86_64

Build
  version: v0.21.0-653-g2b0a
  LLVM: 20.1.8
  bfd: yes
  libdw (DWARF support): yes
  libsystemd (systemd notify support): no

Kernel helpers
  probe_read: yes                  probe_read_str: yes                
  probe_read_user: yes             probe_read_user_str: yes           
  probe_read_kernel: yes           probe_read_kernel_str: yes         
  get_current_cgroup_id: yes       send_signal: yes                   
  override_return: no              get_boot_ns: yes                   
  dpath: yes                       skboutput: yes                     
  get_tai_ns: yes                  get_func_ip: yes                   
  jiffies64: yes                   for_each_map_elem: yes             
  get_ns_current_pid_tgid: yes     lookup_percpu_elem: yes            

Kernel features
  Instruction limit: 1000000       btf: yes                           
  module btf: yes                  map batch: yes                     
  uprobe refcount: yes             

Map types                          
  hash: yes                        array: yes                         
  percpu array: yes                stack_trace: yes                   
  perf_event_array: yes            ringbuf: yes                       

Probe types
  kprobe: yes                      tracepoint: yes                    
  perf_event: yes                  fentry: yes                        
  kprobe_multi: yes                uprobe_multi: no                   
  kprobe_session: yes              iter: yes                          
```

**Comment by jordalgo** [comment]
@martinetd I'm a bit confused. You're reporting this for v0.24 but your bpftrace info says your version is 0.21. 

I tried checking out the 0.24 release branch and I can't reproduce on my system.

**Comment by martinetd** [comment]
`v0.21.0-653-g2b0a` is what git describes prints for the first bad commit that builds ( https://github.com/bpftrace/bpftrace/commit/2b0a0f53032e13e4f38e2510f4f71840a92c811a )-- v0.22 and v0.23 were tagged in branched commits so git describe doesn't see them.
(master has seen v0.24-rc0 after that, so git describe on master will show that instead -- that bad commit is a bit before that)

Anyway, it reproduces on both master and release/0.24.x for me, so that's weird you don't hit the problem.

I assume it depends on what's enabled in the kernel and/or how BTF was built with it, what's your kernel?

FWIW, I don't think it's the llvm version (I reproduced it with llvm 19 and 21 on nixos and llvm 20 on fedora 42)

**Comment by jordalgo** [comment]
> is what git describes prints for the first bad commit that builds

Ah, right. I forgot we had that problem that I had fixed :)

> I assume it depends on what's enabled in the kernel and/or how BTF was built with it, what's your kernel?

My kernel is 6.9.0 (centos). I'm not sure if it's BTF related because tracepoints are unusual in that we get their args from parsing `/sys/kernel/tracing/events/CATEGORY/EVENT/format`, injecting it into the bpftrace code and then clang parsing it into bpftrace's internal SizedType (I know it's wacky).

Just curious, can you use `rawtracepoint:vmlinux:sys_enter` and just utilize the id to identify the system call?

**Comment by martinetd** [comment]
> My kernel is 6.9.0 (centos).

I haven't used centos in too long, sorry -- I just picked up a VM image for centos 10-stream and it's running 6.12 (which reproduces the issue with the static bpftrace binary in https://github.com/bpftrace/bpftrace/releases/tag/v0.24.1 ), while 9-stream seems to be running 5.14 (which didn't have such a tracepoint)

Looking at linux history though that doesn't seem to have changed much recently so I'm still surprised, don't have time to dig through which centos version had a 6.9 kernel right now, happy to test if you can point me to it.

>  I'm not sure if it's BTF related because tracepoints are unusual in that we get their args from parsing /sys/kernel/tracing/events/CATEGORY/EVENT/format, injecting it into the bpftrace code and then clang parsing it into bpftrace's internal SizedType (I know it's wacky).

For what it's worth here's what it looks like here:
```
# cat /sys/kernel/tracing/events/syscalls/sys_enter_landlock_add_rule/format 
name: sys_enter_landlock_add_rule
ID: 1459
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:int __syscall_nr;	offset:8;	size:4;	signed:1;
	field:const int ruleset_fd;	offset:16;	size:8;	signed:0;
	field:const enum landlock_rule_type rule_type;	offset:24;	size:8;	signed:0;
	field:const void *const rule_attr;	offset:32;	size:8;	signed:0;
	field:const __u32 flags;	offset:40;	size:8;	signed:0;

print fmt: "ruleset_fd: 0x%08lx, rule_type: 0x%08lx, rule_attr: 0x%08lx, flags: 0x%08lx", ((unsigned long)(REC->ruleset_fd)), ((unsigned long)(REC->rule_type)), ((unsigned long)(REC->rule_attr)), ((unsigned long)(REC->flags))
```
So `field:const enum landlock_rule_type rule_type` obviously cannot be resolved for some reason..

If I force BTF to load the enum this actually works:
```
# ./src/bpftrace -e 'BEGIN { printf("%d\n", (enum landlock_rule_type) LANDLOCK_RULE_PATH_BENEATH); exit(); }
tracepoint:syscalls:sys_enter_landlock_add_rule {}'
Attached 2 probes
1
```

So we might just be missing some explicit resolution?

**Comment by martinetd** [comment]
> Just curious, can you use rawtracepoint:vmlinux:sys_enter and just utilize the id to identify the system call?

Ah sorry forgot to reply to this -- I assume it works (I can attach at least).

I don't actually need this, it's just the nixos test attaching wildcard that failed and made me look

**Comment by viktormalik** [comment]
FWIW, the same bug existed on 0.23.5, too, it was just not exposed in this case.

If you do:
```
# bpftrace -e 'tracepoint:syscalls:sys_enter_landlock_add_rule { print(args.rule_type) } BEGIN { exit() }'
definitions.h:14:33: error: field has incomplete type 'const enum landlock_rule_type'
definitions.h:14:14: note: forward declaration of 'enum landlock_rule_type'
```
the same failure is back.

The reason why it happens with your example on 0.24.1 is that https://github.com/bpftrace/bpftrace/commit/813f5714f506a7baf5da06501b55a870d4f9f0a0 changed the way we resolve types for tracepoint args - previously, they were only resolved to the depth of the field access starting from `args` while now they are always fully resolved.

I'll have a look why that type is not being resolved.

**Comment by viktormalik** [comment]
The fix turned out to be pretty simple: #4714 

We can backport it to the 0.24.x branch and include it in 0.24.2.

**Comment by jordalgo** [comment]
I didn't have the landlock config enabled on my kernel which is why I wasn't seeing this error.

@viktormalik Why do we unconditionally resolve tracepoint args now even though they might not get used?

**Comment by viktormalik** [comment]
> [@viktormalik](https://github.com/viktormalik) Why do we unconditionally resolve tracepoint args now even though they might not get used?

I think that's one of the side-effects of https://github.com/bpftrace/bpftrace/commit/813f5714f506a7baf5da06501b55a870d4f9f0a0. I'll fix that once I implement parsing tracepoint args from BTF.

**Comment by jordalgo** [comment]
> I'll fix that once I implement parsing tracepoint args from BTF.

Sounds great!

**Comment by martinetd** [comment]
Closing this as done unless you want to keep it open until backported, thank you all again! :)
