### PR TITLE
bpftrace: Fix compilation error

### PR DESCRIPTION
**Pull request by sumanthkorikkar**
FatalUserException() is now relocated to util/exceptions.h. Fix compilation error by adjusting headers in architecture specific files.

Fixes: f3557db5 ("cleanup: split `utils.cpp` into `util` library")

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by jordalgo** [comment]
@sumanthkorikkar I guess this is also broken on the release branch. Do you have a paste of the compilation error?

Also this change looks good, can you just fix the clang format issue and perhaps the relative include paths?

File: src/arch/loongarch64.cpp [hunk 1]
```diff
@@ -1,5 +1,5 @@
 #include "arch.h"
-#include "utils.h"
+#include "../util/exceptions.h"
```
[the remark this answers is not in the document]
Comment (sumanthkorikkar) [reply src/arch/loongarch64.cpp:2]: works without relative path. Will change. Thanks

**Comment by jordalgo** [comment]
@viktormalik Looks like we might need another patch release 😢

**Comment by viktormalik** [comment]
@jordalgo I don't think we do, the split was introduced by f3557db5a363c9cd8058de0b537029ec83c35c8d which is not released, yet.

I'm just wondering why CI didn't catch this.

**Comment by viktormalik** [comment]
> I'm just wondering why CI didn't catch this.

Ah, b/c it's for other arches. Now it makes sense.
